---
- name: Add the user 'idrugalea' 
  azure_rm_virtualmachine:
    resource_group: "{{ rg }}"
    name: "{{ vm_name }}"
    ad_user: idrugalea


- name: Add ssh keys
  authorized_key:
    user: idrugalea
    state: present
    key: '{{ item }}'
  with_file:
    - files/idrugalea


   

