---
- name: Add the user 'idrugalea' 
  user:
    name: idrugalea
    comment: idrugalea

- name: Add ssh keys
  authorized_key:
    user: idrugalea
    state: present
    key: '{{ item }}'
  with_file:
    - files/idrugalea


   

